### ISSUE TITLE
Where can I find some docs?

### ISSUE THREAD

**Issue by keddad** [JonathanVusich/litedb#18]
I find the idea of a simple NoSQL DB, and I wanted to give it a try, but where can I find any docs and/or examples of this thing in use?

**Comment by JonathanVusich** [comment]
Yeah, sorry about that! Documentation is still very much missing from this project. :( I'll try to work on it this week in my spare time. Hope you can put this to good use!

**Comment by JonathanVusich** [comment]
FYI, you can experiment with the database currently, as I have published the 1.0.0 release to PyPi. The code should be fairly well commented, but no useful examples yet.

**Comment by JonathanVusich** [comment]
I have added docs and released version 1.1. Enjoy!
