### ISSUE TITLE
Compatibility with LiteDB from .NET

### ISSUE THREAD

**Issue by raulmd13** [JonathanVusich/litedb#24]
Hi, I'm trying to read liteDB files generate by the LiteDB extension made for .NET.
For what I' have seen, this litedb have exactly the same name but seem to be two different things?

It's posible to read .db files from the .NET implementation in the python one?

**Comment by JonathanVusich** [comment]
Hi @raulmd13, this project is completely separate from the .NET LiteDB project. I apologize for the confusion.
